name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for NPM Update
        run: sleep 5m
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: itsprivate/gatsby-buzzing-starter
          event-type: new_version_with_buzzing_theme
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: itsprivate/rt
          event-type: new_version_with_buzzing_theme
