name: Release
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for NPM Update
        run: sleep 5m
      - name: Repository Dispatch1
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: itsprivate/gatsby-buzzing-starter
          event-type: new_version_with_buzzing_theme
      - name: Repository Dispatch2
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: itsprivate/rt
          event-type: new_version_with_buzzing_theme
      - name: Repository Dispatch3
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: itsprivate/rs
          event-type: new_version_with_buzzing_theme
      - name: Repository Dispatch4
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: itsprivate/hn
          event-type: new_version_with_buzzing_theme
      - name: Repository Dispatch5
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: itsprivate/ph
          event-type: new_version_with_buzzing_theme
      - name: Repository Dispatch6
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository: itsprivate/cmv
          event-type: new_version_with_buzzing_theme
